flags: {}
packages:
  - .
  - location:
      commit: c9a013e58c4e391b7d4b7cd14456fca31e866f27
      git: git@bitbucket.com:nrink/statefulness
      #../statefulness
    extra-dep: true
  - location:
      git: git@github.com:ohua-dev/ohua-core
      commit: 0865d3761a731bba8c838658b21519c358dca6a7
    extra-dep: true
extra-deps:
  - lvish-1.1.4
  - bits-atomic-0.1.3
  - rdtsc-1.3.0.1

resolver: lts-6.35
